### ISSUE TITLE
does not compile under openldap 2.3.43

### ISSUE THREAD

**Issue by plrunner** [opinsys/smbkrb5pwd#9]
In file included from smbkrb5pwd.c:41:
../../../servers/slapd/config.h:116: error: variably modified 'log' at file scope
smbkrb5pwd.c: In function 'smbkrb5pwd_exop_passwd':
smbkrb5pwd.c:512: error: 'Modifications' has no member named 'sml_numvals'
smbkrb5pwd.c:523: error: expected expression before 'long'
smbkrb5pwd.c:525: error: expected expression before 'long'
smbkrb5pwd.c:534: error: 'Modifications' has no member named 'sml_numvals'
smbkrb5pwd.c:545: error: expected expression before 'long'
smbkrb5pwd.c:547: error: expected expression before 'long'
smbkrb5pwd.c:556: error: 'Modifications' has no member named 'sml_numvals'
smbkrb5pwd.c:568: error: expected expression before 'long'
smbkrb5pwd.c:570: error: expected expression before 'long'
smbkrb5pwd.c:579: error: 'Modifications' has no member named 'sml_numvals'
smbkrb5pwd.c: At top level:
smbkrb5pwd.c:660: error: initializer element is not constant
smbkrb5pwd.c:660: error: (near initialization for 'smbkrb5pwd_modules[0].word.bv_len')
smbkrb5pwd.c:661: error: initializer element is not constant
smbkrb5pwd.c:661: error: (near initialization for 'smbkrb5pwd_modules[1].word.bv_len')
smbkrb5pwd.c:881: error: expected declaration specifiers or '...' before 'ConfigReply'
smbkrb5pwd.c:901: error: expected declaration specifiers or '...' before 'ConfigReply'
smbkrb5pwd.c:921: error: expected declaration specifiers or '...' before 'ConfigReply'
make: *** [smbkrb5pwd.lo] Error 1

**Comment by vmlintu** [comment]
smbkrb5pwd has been developed for OpenLDAP 2.4 and it has been tested to work with version 2.4.40. I do not know what kind of changes there have been since the 2.3.xx releases. My understanding is that OpenLDAP developers discourage use of old versions, so updating is probably the best way to get it working.
