### ISSUE TITLE
smbkrb5pwd doesn't compile with OpenLDAP 2.6.9

### ISSUE THREAD

**Issue by Tomek-1** [opinsys/smbkrb5pwd#17]
When I try to build the overlay with slapd 2.6.9 (Debian 13) I got following errors:

`../../../libtool --mode=compile gcc -DSMBKRB5PWD_KADM5_CLNT -g -O2  -I../../../include -I../../../include -I../../../servers/slapd -I/usr/include/mit-krb5  -c smbkrb5pwd.c
libtool: compile:  gcc -DSMBKRB5PWD_KADM5_CLNT -g -O2 -I../../../include -I../../../include -I../../../servers/slapd -I/usr/include/mit-krb5 -c smbkrb5pwd.c  -fPIC -DPIC -o .libs/smbkrb5pwd.o
smbkrb5pwd.c:41:10: fatal error: config.h: No such file or directory
   41 | #include "config.h"
      |          ^~~~~~~~~~
compilation terminated.
make: *** [Makefile:49: smbkrb5pwd.lo] Error 1
`
